# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Encode-JP-Mobile
version:      0.19
version_from: lib/Encode/JP/Mobile.pm
installdirs:  site
requires:
    Encode:                        2.23
    File::ShareDir:                0.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
