---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Encode-JP-Mobile
no_index:
  directory:
    - t
    - inc
requires:
  Encode: 2.23
  File::ShareDir: 0.05
  MIME::Words: 5.428
version: 0.30
